### PR TITLE
A few fixes for the python extension

### LINKED ISSUE #250: relocation R_X86_64_PC32 against absolute symbol `_binary_python_extension_py_size' in section `.text' is disallowed
## Expected Behavior

Building a PRoot binary.

## Actual Behavior

Python extension error when building.

## Steps to Reproduce the Problem

```
make -C src loader.elf loader-m32.elf build.h
make -C src proot
```

## Specifications

  - Proot/Care version: 8c0ccf7db18b5d5ca2f47e1afba7897fb1bb39c0
  - Kernel version: `Linux 49c896f37a82 5.11.0-7612-generic #13~1617215757~20.10~97a8d1a-Ubuntu SMP Thu Apr 1 21:09:17 UTC 2 x86_64 GNU/Linux`
  - Host distribution: Pop!_OS v20.10
  - Guest distribution: Alpine v3.13.0

## Command Output

```terminal
make -C src proot
make: Entering directory '/usr/src/proot/src'
  LD	proot
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: extension/python/python.o: relocation R_X86_64_PC32 against absolute symbol `_binary_python_extension_py_size' in section `.text' is disallowed
collect2: error: ld returned 1 exit status
make: *** [GNUmakefile:179: proot] Error 1
make: Leaving directory '/usr/src/proot/src'
```

### PR DESCRIPTION
**Pull request by yuyichao**
* Fix the command line handler
* Fix linking against the swig generated symbol (Fix  #250)
* Fix linking on python 3.8+

### CODE REVIEW

File: src/cli/proot.h [hunk 1]
```diff
@@ -269,7 +269,7 @@ Copyright (C) 2021 PRoot Developers, licensed under GPL v2 or later.",
 	  .arguments = {
 		{ .name = "-P", .separator = ' ', .value = "string" },
 		{ .name = NULL, .separator = '\0', .value = NULL } },
-	  .handler = handle_option_p,
+	  .handler = handle_option_P,
```
Comment (oxr463) [inline src/cli/proot.h:272]: Yeah, looks like it was confused...instead of the Python extension, that is for the port extension.

**Review by oxr463 — APPROVED** [review]
